package cadastrocontatos.gui;

import cadastrocontatos.controladores.GerenciadorIO;
import cadastrocontatos.controladores.ModeloTabela;
import cadastrocontatos.entidades.Contato;
import cadastrocontatos.entidades.ContatoCliente;
import cadastrocontatos.entidades.ContatoFornecedor;
import cadastrocontatos.entidades.ContatoPessoal;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author luluf
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public PrincipalJFrame() {
        initComponents();
        
        byte[] buffer = GerenciadorIO.carregarIcone();
        ImageIcon icon = new ImageIcon(buffer);
        setIconImage(icon.getImage());
        
        lista_outros = GerenciadorIO.buscarOutrosContatos();
        lista_pessoais = GerenciadorIO.buscarContatosPessoais();
        lista_clientes = GerenciadorIO.buscarClientes();
        lista_fornecedores = GerenciadorIO.buscarFornecedores();
        modeloTabelaCliente = new ModeloTabela(lista_clientes);
        modeloTabelaFornecedor = new ModeloTabela(lista_fornecedores);
        modeloTabelaPessoal = new ModeloTabela(lista_pessoais);
        modeloTabelaOutros = new ModeloTabela(lista_outros);
        tableContatosClientes.setModel(modeloTabelaCliente);
        tableContatosFornecedores.setModel(modeloTabelaFornecedor);
        tableContatosPessoais.setModel(modeloTabelaPessoal);
        tableOutrosContatos.setModel(modeloTabelaOutros);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelInicio = new javax.swing.JPanel();
        uiTitle = new javax.swing.JLabel();
        uiSubtitle = new javax.swing.JLabel();
        uiDev = new javax.swing.JLabel();
        panelCadastroCliente = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnClienteConsultar = new javax.swing.JButton();
        btnClienteAdicionar = new javax.swing.JButton();
        btnClienteRemover = new javax.swing.JButton();
        btnClienteAlterar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableContatosClientes = new javax.swing.JTable();
        panelCadastroFornecedor = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnFornecedorConsultar = new javax.swing.JButton();
        btnFornecedorAdicionar = new javax.swing.JButton();
        btnFornecedorRemover = new javax.swing.JButton();
        btnFornecedorAlterar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableContatosFornecedores = new javax.swing.JTable();
        panelCadastroContatoPessoal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPessoalConsultar = new javax.swing.JButton();
        btnPessoalAdicionar = new javax.swing.JButton();
        btnPessoalRemover = new javax.swing.JButton();
        btnPessoalAlterar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableContatosPessoais = new javax.swing.JTable();
        panelCadastroOutroContato = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnOutroConsultar = new javax.swing.JButton();
        btnOutroAdicionar = new javax.swing.JButton();
        btnOutroRemover = new javax.swing.JButton();
        btnOutroAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOutrosContatos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuInicio = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenuItem();
        menuFornecedor = new javax.swing.JMenuItem();
        menuContatoPessoal = new javax.swing.JMenuItem();
        menuOutroContato = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuFechar = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("iContact");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelInicio.setToolTipText("");
        panelInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelInicio.setName("Inicio"); // NOI18N
        panelInicio.setLayout(new java.awt.GridLayout(3, 1));

        uiTitle.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        uiTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uiTitle.setText("iContact");
        uiTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelInicio.add(uiTitle);

        uiSubtitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        uiSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uiSubtitle.setText("Software de gerenciamento de contatos");
        panelInicio.add(uiSubtitle);

        uiDev.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uiDev.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uiDev.setText("Desenvolvido por Ultimate94");
        uiDev.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        uiDev.setAlignmentY(0.0F);
        panelInicio.add(uiDev);

        jTabbedPane1.addTab("Início", panelInicio);

        panelCadastroCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnClienteConsultar.setText("Consultar");
        btnClienteConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteConsultarActionPerformed(evt);
            }
        });

        btnClienteAdicionar.setText("Adicionar");
        btnClienteAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteAdicionarActionPerformed(evt);
            }
        });

        btnClienteRemover.setText("Remover");
        btnClienteRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteRemoverActionPerformed(evt);
            }
        });

        btnClienteAlterar.setText("Alterar");
        btnClienteAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClienteConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(btnClienteAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClienteRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClienteAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClienteConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClienteAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClienteAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClienteRemover)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableContatosClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableContatosClientes);

        javax.swing.GroupLayout panelCadastroClienteLayout = new javax.swing.GroupLayout(panelCadastroCliente);
        panelCadastroCliente.setLayout(panelCadastroClienteLayout);
        panelCadastroClienteLayout.setHorizontalGroup(
            panelCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCadastroClienteLayout.setVerticalGroup(
            panelCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clientes", panelCadastroCliente);

        panelCadastroFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnFornecedorConsultar.setText("Consultar");
        btnFornecedorConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorConsultarActionPerformed(evt);
            }
        });

        btnFornecedorAdicionar.setText("Adicionar");
        btnFornecedorAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorAdicionarActionPerformed(evt);
            }
        });

        btnFornecedorRemover.setText("Remover");
        btnFornecedorRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorRemoverActionPerformed(evt);
            }
        });

        btnFornecedorAlterar.setText("Alterar");
        btnFornecedorAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFornecedorConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(btnFornecedorAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFornecedorRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFornecedorAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFornecedorConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFornecedorAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFornecedorAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFornecedorRemover)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableContatosFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableContatosFornecedores);

        javax.swing.GroupLayout panelCadastroFornecedorLayout = new javax.swing.GroupLayout(panelCadastroFornecedor);
        panelCadastroFornecedor.setLayout(panelCadastroFornecedorLayout);
        panelCadastroFornecedorLayout.setHorizontalGroup(
            panelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCadastroFornecedorLayout.setVerticalGroup(
            panelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Fornecedores", panelCadastroFornecedor);

        panelCadastroContatoPessoal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnPessoalConsultar.setText("Consultar");
        btnPessoalConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoalConsultarActionPerformed(evt);
            }
        });

        btnPessoalAdicionar.setText("Adicionar");
        btnPessoalAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoalAdicionarActionPerformed(evt);
            }
        });

        btnPessoalRemover.setText("Remover");
        btnPessoalRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoalRemoverActionPerformed(evt);
            }
        });

        btnPessoalAlterar.setText("Alterar");
        btnPessoalAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoalAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPessoalConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(btnPessoalAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPessoalRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPessoalAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPessoalConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPessoalAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPessoalAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPessoalRemover)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableContatosPessoais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableContatosPessoais);

        javax.swing.GroupLayout panelCadastroContatoPessoalLayout = new javax.swing.GroupLayout(panelCadastroContatoPessoal);
        panelCadastroContatoPessoal.setLayout(panelCadastroContatoPessoalLayout);
        panelCadastroContatoPessoalLayout.setHorizontalGroup(
            panelCadastroContatoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroContatoPessoalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCadastroContatoPessoalLayout.setVerticalGroup(
            panelCadastroContatoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroContatoPessoalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroContatoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Contatos Pessoais", panelCadastroContatoPessoal);

        panelCadastroOutroContato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnOutroConsultar.setText("Consultar");
        btnOutroConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutroConsultarActionPerformed(evt);
            }
        });

        btnOutroAdicionar.setText("Adicionar");
        btnOutroAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutroAdicionarActionPerformed(evt);
            }
        });

        btnOutroRemover.setText("Remover");
        btnOutroRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutroRemoverActionPerformed(evt);
            }
        });

        btnOutroAlterar.setText("Alterar");
        btnOutroAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutroAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOutroConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(btnOutroAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOutroRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOutroAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutroConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOutroAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOutroAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOutroRemover)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableOutrosContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableOutrosContatos);

        javax.swing.GroupLayout panelCadastroOutroContatoLayout = new javax.swing.GroupLayout(panelCadastroOutroContato);
        panelCadastroOutroContato.setLayout(panelCadastroOutroContatoLayout);
        panelCadastroOutroContatoLayout.setHorizontalGroup(
            panelCadastroOutroContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroOutroContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCadastroOutroContatoLayout.setVerticalGroup(
            panelCadastroOutroContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroOutroContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroOutroContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Outros contatos", panelCadastroOutroContato);

        jMenu1.setText("Cadastrar");

        menuInicio.setText("Início");
        menuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInicioActionPerformed(evt);
            }
        });
        jMenu1.add(menuInicio);

        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        jMenu1.add(menuCliente);

        menuFornecedor.setText("Fornecedor");
        menuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(menuFornecedor);

        menuContatoPessoal.setText("Contato Pessoal");
        menuContatoPessoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContatoPessoalActionPerformed(evt);
            }
        });
        jMenu1.add(menuContatoPessoal);

        menuOutroContato.setText("Outro Contato");
        menuOutroContato.setToolTipText("");
        menuOutroContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOutroContatoActionPerformed(evt);
            }
        });
        jMenu1.add(menuOutroContato);
        jMenu1.add(jSeparator1);

        menuFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuFechar.setText("Fechar");
        menuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFecharActionPerformed(evt);
            }
        });
        jMenu1.add(menuFechar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tab 1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFecharActionPerformed
        dispose();
    }//GEN-LAST:event_menuFecharActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFornecedorActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_menuFornecedorActionPerformed

    private void menuContatoPessoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContatoPessoalActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_menuContatoPessoalActionPerformed

    private void menuOutroContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOutroContatoActionPerformed
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_menuOutroContatoActionPerformed

    private void menuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicioActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_menuInicioActionPerformed

    /*********************
     * Tab Outros Contatos
     *********************/
    
    private void btnOutroConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutroConsultarActionPerformed
        int index = tableOutrosContatos.getSelectedRow();
        if(index >= 0){
            Contato contato = modeloTabelaOutros.getContato(index);
            OutroJDialog.executar(null, OperacaoCadastro.ocConsultar, contato);
        }
    }//GEN-LAST:event_btnOutroConsultarActionPerformed

    private void btnOutroAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutroAdicionarActionPerformed
        Contato contato = new Contato();
        boolean confirmado = OutroJDialog.executar(this, OperacaoCadastro.ocIncluir, contato);
        if(confirmado){
            modeloTabelaOutros.insertContato(contato);
        }
    }//GEN-LAST:event_btnOutroAdicionarActionPerformed

    private void btnOutroAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutroAlterarActionPerformed
        int index = tableOutrosContatos.getSelectedRow();
        if(index >= 0){
            Contato contato = modeloTabelaOutros.getContato(index);
            boolean confirmado = OutroJDialog.executar(this, OperacaoCadastro.ocAlterar, contato);
            if(confirmado){
                modeloTabelaOutros.setContato(index, contato);
            }
        }
    }//GEN-LAST:event_btnOutroAlterarActionPerformed

    private void btnOutroRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutroRemoverActionPerformed
        int index = tableOutrosContatos.getSelectedRow();
        if(index >= 0){
            int resp = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir esse contato?", "Excluir contato", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.NO_OPTION) return;
            modeloTabelaOutros.deleteContato(index);
        }
    }//GEN-LAST:event_btnOutroRemoverActionPerformed

    /*********************
     * Tab Contatos Pessoais
     *********************/
    
    private void btnPessoalConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoalConsultarActionPerformed
        int index = tableContatosPessoais.getSelectedRow();
        if(index >= 0){
            ContatoPessoal contato = (ContatoPessoal) modeloTabelaPessoal.getContato(index);
            PessoalJDialog.executar(null, OperacaoCadastro.ocConsultar, contato);
        }
    }//GEN-LAST:event_btnPessoalConsultarActionPerformed

    private void btnPessoalAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoalAdicionarActionPerformed
        ContatoPessoal contato = new ContatoPessoal();
        boolean confirmado = PessoalJDialog.executar(this, OperacaoCadastro.ocIncluir, contato);
        if(confirmado){
            modeloTabelaPessoal.insertContato(contato);
        }
    }//GEN-LAST:event_btnPessoalAdicionarActionPerformed

    private void btnPessoalAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoalAlterarActionPerformed
        int index = tableContatosPessoais.getSelectedRow();
        if(index >= 0){
            ContatoPessoal contato = (ContatoPessoal) modeloTabelaPessoal.getContato(index);
            boolean confirmado = PessoalJDialog.executar(this, OperacaoCadastro.ocAlterar, contato);
            if(confirmado){
                modeloTabelaPessoal.setContato(index, contato);
            }
        }
    }//GEN-LAST:event_btnPessoalAlterarActionPerformed

    private void btnPessoalRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoalRemoverActionPerformed
        
        int index = tableContatosPessoais.getSelectedRow();
        if(index >= 0){
            int resp = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir esse contato?", "Excluir contato", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.NO_OPTION) return;
            modeloTabelaPessoal.deleteContato(index);
        }
    }//GEN-LAST:event_btnPessoalRemoverActionPerformed
    
    /*********************
    * Tab Contatos Fornecedores
    *********************/
    
    private void btnFornecedorConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorConsultarActionPerformed
        int index = tableContatosFornecedores.getSelectedRow();
        if(index >= 0){
            ContatoFornecedor contato = (ContatoFornecedor) modeloTabelaFornecedor.getContato(index);
            FornecedorJDialog.executar(null, OperacaoCadastro.ocConsultar, contato);
        }
    }//GEN-LAST:event_btnFornecedorConsultarActionPerformed

    private void btnFornecedorAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorAdicionarActionPerformed
        ContatoFornecedor contato = new ContatoFornecedor();
        boolean confirmado = FornecedorJDialog.executar(this, OperacaoCadastro.ocIncluir, contato);
        if(confirmado){
            modeloTabelaFornecedor.insertContato(contato);
        }
    }//GEN-LAST:event_btnFornecedorAdicionarActionPerformed

    private void btnFornecedorAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorAlterarActionPerformed
        int index = tableContatosFornecedores.getSelectedRow();
        if(index >= 0){
            ContatoFornecedor contato = (ContatoFornecedor) modeloTabelaFornecedor.getContato(index);
            boolean confirmado = FornecedorJDialog.executar(this, OperacaoCadastro.ocAlterar, contato);
            if(confirmado){
                modeloTabelaFornecedor.setContato(index, contato);
            }
        }
    }//GEN-LAST:event_btnFornecedorAlterarActionPerformed

    private void btnFornecedorRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorRemoverActionPerformed
        int index = tableContatosFornecedores.getSelectedRow();
        if(index >= 0){
            int resp = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir esse contato?", "Excluir contato", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.NO_OPTION) return;
            modeloTabelaFornecedor.deleteContato(index);
        }
    }//GEN-LAST:event_btnFornecedorRemoverActionPerformed
    
    /*********************
    * Tab Contatos Clientes
    *********************/
    
    private void btnClienteConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteConsultarActionPerformed
        int index = tableContatosClientes.getSelectedRow();
        if(index >= 0){
            ContatoCliente contato = (ContatoCliente) modeloTabelaCliente.getContato(index);
            ClienteJDialog.executar(null, OperacaoCadastro.ocConsultar, contato);
        }
    }//GEN-LAST:event_btnClienteConsultarActionPerformed

    private void btnClienteAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteAdicionarActionPerformed
        ContatoCliente contato = new ContatoCliente();
        boolean confirmado = ClienteJDialog.executar(this, OperacaoCadastro.ocIncluir, contato);
        if(confirmado){
            modeloTabelaCliente.insertContato(contato);
        }
    }//GEN-LAST:event_btnClienteAdicionarActionPerformed

    private void btnClienteAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteAlterarActionPerformed
        int index = tableContatosClientes.getSelectedRow();
        if(index >= 0){
            ContatoCliente contato = (ContatoCliente) modeloTabelaCliente.getContato(index);
            boolean confirmado = ClienteJDialog.executar(this, OperacaoCadastro.ocAlterar, contato);
            if(confirmado){
                modeloTabelaCliente.setContato(index, contato);
            }
        }
    }//GEN-LAST:event_btnClienteAlterarActionPerformed

    private void btnClienteRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteRemoverActionPerformed
        int index = tableContatosClientes.getSelectedRow();
        if(index >= 0){
            int resp = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir esse contato?", "Excluir contato", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.NO_OPTION) return;
            modeloTabelaCliente.deleteContato(index);
        }
    }//GEN-LAST:event_btnClienteRemoverActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        GerenciadorIO.salvarClientes(lista_clientes);
        GerenciadorIO.salvarContatosPessoais(lista_pessoais);
        GerenciadorIO.salvarFornecedores(lista_fornecedores);
        GerenciadorIO.salvarOutrosContatos(lista_outros);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        GerenciadorIO.criarArquivos();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }
    List<Contato> lista_outros;
    List<Contato> lista_pessoais;
    List<Contato> lista_clientes;
    List<Contato> lista_fornecedores;
    private ModeloTabela modeloTabelaCliente;
    private ModeloTabela modeloTabelaPessoal;
    private ModeloTabela modeloTabelaFornecedor;
    private ModeloTabela modeloTabelaOutros;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteAdicionar;
    private javax.swing.JButton btnClienteAlterar;
    private javax.swing.JButton btnClienteConsultar;
    private javax.swing.JButton btnClienteRemover;
    private javax.swing.JButton btnFornecedorAdicionar;
    private javax.swing.JButton btnFornecedorAlterar;
    private javax.swing.JButton btnFornecedorConsultar;
    private javax.swing.JButton btnFornecedorRemover;
    private javax.swing.JButton btnOutroAdicionar;
    private javax.swing.JButton btnOutroAlterar;
    private javax.swing.JButton btnOutroConsultar;
    private javax.swing.JButton btnOutroRemover;
    private javax.swing.JButton btnPessoalAdicionar;
    private javax.swing.JButton btnPessoalAlterar;
    private javax.swing.JButton btnPessoalConsultar;
    private javax.swing.JButton btnPessoalRemover;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuContatoPessoal;
    private javax.swing.JMenuItem menuFechar;
    private javax.swing.JMenuItem menuFornecedor;
    private javax.swing.JMenuItem menuInicio;
    private javax.swing.JMenuItem menuOutroContato;
    private javax.swing.JPanel panelCadastroCliente;
    private javax.swing.JPanel panelCadastroContatoPessoal;
    private javax.swing.JPanel panelCadastroFornecedor;
    private javax.swing.JPanel panelCadastroOutroContato;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JTable tableContatosClientes;
    private javax.swing.JTable tableContatosFornecedores;
    private javax.swing.JTable tableContatosPessoais;
    private javax.swing.JTable tableOutrosContatos;
    private javax.swing.JLabel uiDev;
    private javax.swing.JLabel uiSubtitle;
    private javax.swing.JLabel uiTitle;
    // End of variables declaration//GEN-END:variables
}
